controller:
  admin:
    existingSecret: jenkins-admin
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

  containerEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: aws-access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: aws-secret-access-key
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: github-token
    - name: TF_STATE_BUCKET
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: tf-state-bucket
    - name: MAIL_SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mail-smtp-host
    - name: MAIL_SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mail-smtp-port
    - name: MAIL_SMTP_USER
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mail-smtp-user
    - name: MAIL_SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jenkins-secrets
          key: mail-smtp-password

  serviceType: ClusterIP

  numExecutors: 0
  initializeOnce: true

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - pipeline-stage-view
    - job-dsl
    - aws-credentials
    - credentials
    - plain-credentials
    - ssh-credentials
    - junit
    - timestamper
    - email-ext
    # - workflow-cps-global-lib
    
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins configured via Helm and JCasC for Terraform CI/CD"
      
      tools: |
        tool:
          git:
            installations:
            - home: "git"
              name: "Default"
      
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - aws:
                      id: "aws-creds"
                      accessKey: "${AWS_ACCESS_KEY_ID}"
                      secretKey: "${AWS_SECRET_ACCESS_KEY}"
                      scope: GLOBAL
                      description: "AWS credentials for Terraform pipeline"

                  - string:
                      id: "github-token"
                      secret: "${GITHUB_TOKEN}"
                      scope: GLOBAL
                      description: "GitHub token for Jenkins pipeline access"

                  - string:
                      id: "tf-state-bucket"
                      secret: "${TF_STATE_BUCKET}"
                      scope: GLOBAL
                      description: "Terraform remote state bucket"

                  - usernamePassword:
                      id: "gmail_cred"
                      username: "${MAIL_SMTP_USER}"
                      password: "${MAIL_SMTP_PASSWORD}"
                      usernameSecret: true
                      scope: GLOBAL
                      description: "Gmail SMTP credentials for Jenkins notifications"

      email: |
        unclassified:
          location:
            adminAddress: "${MAIL_SMTP_USER}"
          buildDiscarders:
            configuredBuildDiscarders:
            - "jobBuildDiscarder"
          email-ext:
            mailAccount:
              credentialsId: "gmail_cred"
              smtpHost: "${MAIL_SMTP_HOST}"
              smtpPort: "${MAIL_SMTP_PORT}"
              useSsl: true
          mailer:
            authentication:
              username: "${MAIL_SMTP_USER}"
              password: "${MAIL_SMTP_PASSWORD}"
            charset: "UTF-8"
            smtpHost: "${MAIL_SMTP_HOST}"
            smtpPort: "${MAIL_SMTP_PORT}"
            useSsl: true
            useTls: false

      libraries: |
        unclassified:
          globalLibraries:
            libraries:
              - name: "jenkins-terraform-shared-lib"
                defaultVersion: "master"
                implicit: false
                allowVersionOverride: true
                retriever:
                  modernSCM:
                    scm:
                      gitSource:
                        remote: "https://github.com/simonangel-fong/Jenkins_Demo_Terraform_Multi_Env.git"
                        credentialsId: "github-token"

      jobs: |
        jobs:
          - script: |
              pipelineJob('master-pipeline') {
                description('Terraform pipeline for master branch')

                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/simonangel-fong/Jenkins_Demo_Terraform_Multi_Env.git')
                          credentials('github-token')
                        }
                        branches('*/master')
                      }
                    }
                    scriptPath('Jenkinsfile')
                  }
                }
              }

persistence:
  enabled: true
  size: 8Gi

agent:
  enabled: true

  maxRequestsPerHostStr: 32
  retentionTimeout: 5
  waitForPodSec: 120

  podTemplates:
    agent: |
      - name: agent
        label: agent-terraform
        serviceAccount: jenkins
        containers:
          - name: git
            image: alpine/git:2.45.2
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
            resourceRequestCpu: "100m"
            resourceRequestMemory: "128Mi"
            resourceLimitCpu: "500m"
            resourceLimitMemory: "512Mi"
