pipeline {
  agent {
    kubernetes {
      label 'agent-terraform'
      defaultContainer 'terraform'
    }
  }

  options {
    timestamps()
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '20'))
  }

  environment {
    TF_IN_AUTOMATION = 'true'
    TF_ROOT          = 'infra'
    TF_PLAN_FILE     = 'tfplan.binary'
    TF_PLAN_TXT      = 'tfplan.txt'
    TF_VAR_FILE      = 'env/dev/terraform.tfvars'

    AWS_REGION       = 'ca-central-1'
    TF_STATE_BUCKET  = "simonangelfong-terraform-backend"
    TF_STATE_KEY     = 'jenkins-terraform/sandbox/terraform.tfstate'
  }

  triggers {
    // optional if you use webhook instead
    pollSCM('H/5 * * * *')
  }

  stages {
    // stage('Branch Guard') {
    //   steps {
    //     script {
    //       def branchName = env.BRANCH_NAME ?: sh(
    //         script: 'git rev-parse --abbrev-ref HEAD',
    //         returnStdout: true
    //       ).trim()

    //       echo "Detected branch: ${branchName}"

    //       if (!branchName.startsWith('feature/')) {
    //         error("This pipeline only supports feature/* branches. Current branch: ${branchName}")
    //       }
    //     }
    //   }
    // }

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('fmt') {
      steps {
        dir("${env.TF_ROOT}") {
          echo "Terraform Root Dir: ${env.TF_ROOT}"
          sh '''
            terraform fmt -recursive -check
          '''
        }
      }
    }

    stage('init') {
      steps {
        dir("${env.TF_ROOT}") {
          echo "${TF_STATE_BUCKET}"
          sh '''
            terraform init \
              -input=false \
              -reconfigure \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="key=${TF_STATE_KEY}" \
              -backend-config="region=${AWS_REGION}" \
              -backend-config="encrypt=true"
          '''
        }
      }
    }

    // stage('validate') {
    //   steps {
    //     dir("${env.TF_ROOT}") {
    //       sh '''
    //         terraform validate
    //       '''
    //     }
    //   }
    // }

    // stage('plan (dev)') {
    //   steps {
    //     dir("${env.TF_ROOT}") {
    //       sh '''
    //         terraform plan \
    //           -input=false \
    //           -var-file="${TF_VAR_FILE}" \
    //           -out="${TF_PLAN_FILE}"

    //         terraform show -no-color "${TF_PLAN_FILE}" > "${TF_PLAN_TXT}"
    //       '''
    //     }
    //   }
    // }

    // stage('archive') {
    //   steps {
    //     archiveArtifacts artifacts: "${env.TF_ROOT}/${env.TF_PLAN_FILE}, ${env.TF_ROOT}/${env.TF_PLAN_TXT}", fingerprint: true
    //   }
    // }
  }

  post {
    always {
      echo 'Pipeline finished.'
    }

    success {
      echo 'Terraform validation and plan completed successfully.'
    }

    failure {
      echo 'Pipeline failed. Check fmt / validate / plan output.'
    }
  }
}